### ISSUE TITLE
中文名字时无法登录，读取配置文件需要utf-8

### ISSUE THREAD

**Issue by lxyddice** [XCWQW1/iirosebot#50]
作者您好，在登录时遇到名字为乱码的问题，报错如下：

![image](https://github.com/XCWQW1/iirosebot/assets/95132858/a79f02e3-45cc-4e9e-8694-78968511f071)

![image](https://github.com/XCWQW1/iirosebot/assets/95132858/32209618-edb1-4b23-8233-8027db3274bc)

自行修改了  API/api_load_config.py  的文件读取编码的代码后就好了

![image](https://github.com/XCWQW1/iirosebot/assets/95132858/06761eb2-5c5d-4d87-9724-f3f05a632e80)

**Comment by XCWQW1** [comment]
感谢您的反馈，将会在下个版本中修复

**Comment by XCWQW1** [comment]
已对所有读写文件代码添加encoding='utf-8'，希望后面不会出这个问题吧

**Comment by XCWQW1** [comment]
#51
